addSbtPlugin("org.scalameta"  % "sbt-scalafmt"      % "2.5.5")
addSbtPlugin("com.eed3si9n"   % "sbt-projectmatrix" % "0.11.0")
addSbtPlugin("com.github.sbt" % "sbt-ci-release"    % "1.11.2")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"     % "2.3.1")
addSbtPlugin("org.scalameta"  % "sbt-mdoc"          % "2.8.0")
addSbtPlugin("com.github.sbt" % "sbt-unidoc"        % "0.6.0")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"     % "0.13.1")
