addSbtPlugin("org.scalameta"  % "sbt-scalafmt"   % "2.5.6")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.11.2")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"  % "2.4.2")
addSbtPlugin("org.scalameta"  % "sbt-mdoc"       % "2.8.0")
addSbtPlugin("com.github.sbt" % "sbt-unidoc"     % "0.6.0")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"  % "0.13.1")
