addSbtPlugin("org.scalameta"  % "sbt-scalafmt"      % "2.5.5")
addSbtPlugin("com.eed3si9n"   % "sbt-projectmatrix" % "0.11.0")
addSbtPlugin("com.github.sbt" % "sbt-ci-release"    % "1.11.1")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"     % "2.3.1")
addSbtPlugin("org.scalameta"  % "sbt-mdoc"          % "2.7.1")
addSbtPlugin("com.github.sbt" % "sbt-unidoc"        % "0.5.0")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"     % "0.13.1")
