name: Release

on:
  push:
    branches: [ master, main ]
  release:
    types: [ published ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  JDK_JAVA_OPTIONS: -XX:+PrintCommandLineFlags -Xms6G -Xmx6G -Xss4M -XX:+UseG1GC -XX:ReservedCodeCacheSize=512M -XX:NonProfiledCodeHeapSize=256M # JDK_JAVA_OPTIONS is _the_ env. variable to use for modern Java
  SBT_OPTS: -XX:+PrintCommandLineFlags -Xms6G -Xmx6G -Xss4M -XX:+UseG1GC -XX:ReservedCodeCacheSize=512M -XX:NonProfiledCodeHeapSize=256M # Needed for sbt

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: env
        shell: bash
      - uses: actions/checkout@v4
      - uses: sbt/setup-sbt@v1
      - uses: coursier/cache-action@v6
      - uses: olafurpg/setup-gpg@v3
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          check-latest: true
      - run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
